name: Rubicore
favicon: null
layout_spectrum: 0.15054029505699873
typography_spectrum: 0.8368800503667444
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.13616709457710385
  lightness: 0.17858069576323032
  saturation: 0.1135215419344604
  rhythmicContrast: 0.22043843218125403
purpose: []
